=== api-evangelist/root/json-schema/call.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "call",
  "type": "object",
  "required": [
    "call_id",
    "created_at",
    "call_status",
    "direction",
    "from_number",
    "topic"
  ],
  "properties": {
    "call_id": {
      "type": "string",
      "description": "Must be a UUID. The unique identifier of the call."
    },
    "policyholder_id": {
      "type": [
        "string",
        "null"
      ],
      "description": "Must be a UUID. The unique identifier of the [policyholder](ref:policyholder) associated with the call. `null` if no policyholder is linked."
    },
    "policyholder": {
      "type": [
        "object",
        "null"
      ],
      "description": "The [policyholder](ref:policyholder) object associated with this call. Only included when `include=policyholder` query parameter is specified."
    },
    "claim_id": {
      "type": [
        "string",
        "null"
      ],
      "description": "Must be a UUID. The unique identifier of the [claim](ref:claim) associated with the call. `null` if no claim is linked."
    },
    "created_at": {
      "type": "string",
      "format": "date-time",
      "description": "The timestamp at which the call was logged."
    },
    "call_status": {
      "type": "string",
      "description": "The current status of the call.",
      "enum": [
        "initiated",
        "ringing",
        "in-progress",
        "completed",
        "busy",
        "no-answer"
      ]
    },
    "direction": {
      "type": "string",
      "description": "The direction of the call.",
      "enum": [
        "inbound",
        "outbound"
      ]
    },
    "from_number": {
      "type": "string",
      "description": "The initiating phone number of the call."
    },
    "to_number": {
      "type": [
        "string",
        "null"
      ],
      "description": "The receiving phone number of the call. `null` if not available."
    },
    "topic": {
      "type": "string",
      "description": "The topic category of the call.",
      "enum": [
        "claims",
        "complaints",
        "general"
      ]
    },
    "recording_url": {
      "type": [
        "string",
        "null"
      ],
      "description": "The URL of the call recording. This is available if the call successfully connected and only once the call is completed. `null` if no recording exists."
    },
    "call_duration": {
      "type": [
        "string",
        "null"
      ],
      "description": "The duration of the call in seconds. May be `null` if not recorded."
    }
  },
  "example": {
    "call_id": "d3d13c48-4dc3-4816-8d01-de3215878225",
    "policyholder_id": "8349345c-a6c5-4bf9-8ebb-6bbfc1628715",
    "claim_id": "673b8081-9668-4136-97cc-6ae0debda083",
    "created_at": "2017-10-16T10:12:02.872Z",
    "call_status": "completed",
    "direction": "outbound",
    "from_number": "0721234567",
    "to_number": "0821234567",
    "topic": "general",
    "recording_url": "https://sandbox.root.co.za/v1/files/download/ccbd249e-a404-11ea-8f4a-47e769474b83/Recording0001.mp3",
    "call_duration": "72"
  }
}

=== api-evangelist/root/examples/create-call-response-200.json
{
  "call_id": "d3d13c48-4dc3-4816-8d01-de3215878225",
  "policyholder_id": "8349345c-a6c5-4bf9-8ebb-6bbfc1628715",
  "claim_id": "673b8081-9668-4136-97cc-6ae0debda083",
  "created_at": "2017-10-16T10:12:02.872Z",
  "call_status": "completed",
  "direction": "outbound",
  "from_number": "0721234567",
  "to_number": "0821234567",
  "topic": "general",
  "recording_url": "https://sandbox.root.co.za/v1/files/download/ccbd249e-a404-11ea-8f4a-47e769474b83/Recording0001.mp3",
  "call_duration": "72"
}

=== api-evangelist/root/examples/fetch-calls-response-200.json
[
  {
    "call_id": "0ac6dffb-bd15-4829-b96d-e2c1abe61d3a",
    "policyholder_id": "8349345c-a6c5-4bf9-8ebb-6bbfc1628715",
    "claim_id": null,
    "created_at": "2017-11-26T11:14:59.777Z",
    "call_status": "completed",
    "direction": "inbound",
    "from_number": "+27823378000",
    "to_number": "+27821234567",
    "topic": "general",
    "recording_url": "https://recordingurl.com",
    "call_duration": "5"
  }
]
