=== api-evangelist/root/json-schema/data-store-entity.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "data-store-entity",
  "type": "object",
  "required": [
    "data_store_entity_id",
    "organization_id",
    "data",
    "created_by",
    "created_at",
    "updated_at",
    "updated_by",
    "data_store"
  ],
  "properties": {
    "data_store_entity_id": {
      "type": "string",
      "description": "Must be a UUID. The unique identifier of the data store entity."
    },
    "organization_id": {
      "type": "string",
      "description": "Must be a UUID. The unique identifier of the organization the data store belongs to."
    },
    "data": {
      "type": "object",
      "description": "The data store data."
    },
    "created_by": {
      "type": "object",
      "description": "An object indicating the user or API key that created the data store entity."
    },
    "created_at": {
      "type": "string",
      "format": "date-time",
      "description": "The time at which the data entity store entity was created."
    },
    "updated_at": {
      "type": "string",
      "format": "date-time",
      "description": "The time at which the data store entity was last updated."
    },
    "updated_by": {
      "type": "object",
      "description": "An object indicating the user or API key that last updated the data store entity."
    },
    "data_store": {
      "$ref": "#/components/schemas/data-store"
    }
  },
  "example": {
    "data_store_entity_id": "424312b7-6d8f-424f-bf3e-af1384444424",
    "organization_id": "952bfef5-7517-47ff-bf41-08c5a66c52db",
    "data": {
      "name": "Apple iPhone X",
      "price": 1000000
    },
    "created_by": {
      "type": "api_key",
      "id": "420df14d-b09d-4d89-84a8-8e3118c9ca23",
      "owner_id": "00000000-0000-0000-0000-000000000001"
    },
    "created_at": "2021-01-28T10:00:24.809Z",
    "updated_at": "2021-01-28T10:00:24.809Z",
    "updated_by": {
      "type": "api_key",
      "id": "420df14d-b09d-4d89-84a8-8e3118c9ca23",
      "owner_id": "00000000-0000-0000-0000-000000000001"
    },
    "data_store": {
      "data_store_id": "6e91fe74-aa56-4b4e-8f68-636d23d5706f",
      "key": "devices",
      "schema": {
        "type": "object",
        "async": true,
        "required": [
          "name",
          "price"
        ],
        "properties": {
          "name": {
            "type": "string"
          },
          "price": {
            "type": "number"
          }
        }
      },
      "description": "Devices data store",
      "name": "devices",
      "updated_at": "2021-01-28T10:00:17.773Z",
      "updated_by": {
        "type": "api_key",
        "id": "420df14d-b09d-4d89-84a8-8e3118c9ca23",
        "owner_id": "00000000-0000-0000-0000-000000000001"
      }
    }
  }
}

=== api-evangelist/root/examples/archive-data-store-entity-response-200.json
{
  "data_store_entity_id": "424312b7-6d8f-424f-bf3e-af1384444424",
  "organization_id": "952bfef5-7517-47ff-bf41-08c5a66c52db",
  "data": {
    "name": "Samsung S20",
    "price": 1000000
  },
  "created_by": {
    "type": "api_key",
    "id": "420df14d-b09d-4d89-84a8-8e3118c9ca23",
    "owner_id": "00000000-0000-0000-0000-000000000001"
  },
  "created_at": "2021-01-28T10:00:24.809Z",
  "updated_at": "2021-01-28T10:00:24.809Z",
  "updated_by": {
    "type": "api_key",
    "id": "420df14d-b09d-4d89-84a8-8e3118c9ca23",
    "owner_id": "00000000-0000-0000-0000-000000000001"
  },
  "data_store": {
    "data_store_id": "6e91fe74-aa56-4b4e-8f68-636d23d5706f",
    "key": "devices",
    "schema": {
      "type": "object",
      "async": true,
      "required": [
        "name",
        "price"
      ],
      "properties": {
        "name": {
          "type": "string"
        },
        "price": {
          "type": "number"
        }
      }
    },
    "description": "Devices data store",
    "name": "devices",
    "updated_at": "2021-01-28T10:00:17.773Z",
    "updated_by": {
      "type": "api_key",
      "id": "420df14d-b09d-4d89-84a8-8e3118c9ca23",
      "owner_id": "00000000-0000-0000-0000-000000000001"
    }
  }
}
