=== api-evangelist/root/json-schema/data-export-run.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "data-export-run",
  "type": "object",
  "required": [
    "data_export_run_id",
    "scheduled_data_export_id",
    "created_at",
    "status"
  ],
  "properties": {
    "data_export_run_id": {
      "type": "string",
      "description": "Must be a UUID. The unique identifier of the data export run."
    },
    "scheduled_data_export_id": {
      "type": "string",
      "description": "Must be a UUID. The unique identifier of the scheduled data export that the run belongs to."
    },
    "created_at": {
      "type": "string",
      "format": "date-time",
      "description": "The time at which the data export run was created."
    },
    "completed_at": {
      "type": "string",
      "format": "date-time",
      "description": "The time at which the data export run completed."
    },
    "status": {
      "type": "string",
      "description": "The current status of the data export run. One of `in_progress`, `failed`, or `complete`."
    },
    "file_id": {
      "type": [
        "string",
        "null"
      ],
      "description": "The file created during the run, if successful."
    }
  },
  "example": {
    "data_export_run_id": "34233912-c91f-4dc9-bfed-c10d16be26af",
    "scheduled_data_export_id": "4ab082f2-864e-4bcf-bc17-75664a25f2e1",
    "created_at": "2019-03-09T08:07:59.044Z",
    "completed_at": "2019-03-09T08:08:02.178Z",
    "status": "complete",
    "file_id": "74ce9562-4242-11e9-904a-7b14ba20f082"
  }
}

=== api-evangelist/root/examples/retrieve-data-export-run-response-200.json
{
  "data_export_run_id": "34233912-c91f-4dc9-bfed-c10d16be26af",
  "scheduled_data_export_id": "4ab082f2-864e-4bcf-bc17-75664a25f2e1",
  "created_at": "2019-03-09T08:07:59.044Z",
  "completed_at": "2019-03-09T08:08:02.178Z",
  "status": "complete",
  "file_id": "74ce9562-4242-11e9-904a-7b14ba20f082"
}
