=== api-evangelist/root/json-schema/secret-keys.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "secret-keys",
  "type": "object",
  "required": [
    "type",
    "key",
    "created_at",
    "created_by",
    "updated_at",
    "updated_by"
  ],
  "properties": {
    "secret_key_id": {
      "type": "string",
      "description": "Must be a UUID. The unique identifier of the secret key."
    },
    "organization_id": {
      "type": "string",
      "description": "The identifier of the organization."
    },
    "environment": {
      "type": "string",
      "description": "The environment associated with the secret key."
    },
    "description": {
      "type": "string",
      "description": "A description of the secret key."
    },
    "type": {
      "type": "string",
      "description": "This field uniquely identifies the secret key.\n"
    },
    "key": {
      "type": "string",
      "description": "The encrypted value of the secret key."
    },
    "created_at": {
      "type": "string",
      "format": "date-time",
      "description": "Time at which the secret key was created."
    },
    "created_by": {
      "type": "object",
      "description": "An object indicating the user or API key that created the secret key.",
      "properties": {
        "id": {
          "type": "string",
          "description": "The identifier of the creator."
        },
        "type": {
          "type": "string",
          "description": "The type of the creator (e.g., user, API)."
        }
      }
    },
    "updated_at": {
      "type": "string",
      "format": "date-time",
      "description": "Time at which the secret key was last updated."
    },
    "updated_by": {
      "type": "object",
      "description": "An object indicating the user or API key that last updated the secret key.",
      "properties": {
        "id": {
          "type": "string",
          "description": "The identifier of the updater."
        },
        "type": {
          "type": "string",
          "description": "The type of the updater (e.g., user, API)."
        }
      }
    }
  },
  "example": {
    "organization_id": "4ce6ad99-9576-4d28-84ba-c30d2d536cbe",
    "secret_key_id": "43c13dc8-2c19-402c-bb70-a7deb56b9f38",
    "type": "test",
    "key": "your_api_key_value",
    "description": "API Key for Integration X",
    "created_at": "2023-01-10T12:34:56.789Z",
    "created_by": {
      "id": "00000000-0000-0000-0000-000000000001",
      "type": "user"
    },
    "updated_at": "2023-01-10T12:34:56.789Z",
    "updated_by": {
      "id": "00000000-0000-0000-0000-000000000001",
      "type": "user"
    }
  }
}

=== api-evangelist/root/examples/upsert-secret-key-response-200.json
{
  "organization_id": "4ce6ad99-9576-4d28-84ba-c30d2d536cbe",
  "secret_key_id": "43c13dc8-2c19-402c-bb70-a7deb56b9f38",
  "type": "test",
  "key": "your_api_key_value",
  "description": "API Key for Integration X",
  "created_at": "2023-01-10T12:34:56.789Z",
  "created_by": {
    "id": "00000000-0000-0000-0000-000000000001",
    "type": "user"
  },
  "updated_at": "2023-01-10T12:34:56.789Z",
  "updated_by": {
    "id": "00000000-0000-0000-0000-000000000001",
    "type": "user"
  }
}
